const DB = {
    groups: {
        mission: {
            name: "Missions",
            color: "#E6C565",
        },
        defensive: {
            name: "Defensive",
            color: "#53833F",
        },
        backpacks: {
            name: "Supply: Backpacks",
            color: "#4FB3CF",
        },
        weapons: {
            name: "Supply: Support Weapons",
            color: "#4FB3CF",
        },
        orbital: {
            name: "Offensive: Orbital",
            color: "#CB4C3E",
        },
        eagle: {
            name: "Offensive: Eagle",
            color: "#CB4C3E",
        },
        vehicles: {
            name: "Supply: Vehicles",
            color: "#4FB3CF",
        },
    },
    stratagems: [
        {
            name: "Resupply",
            icon: "ResupplyIcon",
            code: "SSWD",
            key: "mission",
        },
        {
            name: "SOS Beacon",
            icon: "SOSicon",
            code: "WSDW",
            key: "mission",
        },
        {
            name: "Reinforce",
            icon: "Reinforceicon",
            code: "WSDAW",
            key: "mission",
        },
        {
            name: "NUX-223 Hellbomb",
            icon: "Hellbomb_Icon",
            code: "SWASWDSW",
            key: "mission",
        },
        {
            name: "SSSD Delivery",
            icon: "DeliverSSSDicon",
            code: "SSSWW",
            key: "mission",
        },
        {
            name: "Upload Data",
            icon: "DeliverSSSDicon",
            code: "ADWWW",
            key: "mission",
        },
        {
            name: "Eagle Rearm",
            icon: "HD2_Eagle_Rearm_Icon",
            code: "WWAWD",
            key: "mission",
        },
        {
            name: "Seismic Probe",
            icon: "Seismic_probe_icon",
            code: "WWADSS",
            key: "mission",
        },
        {
            name: "SEAF Artillery",
            icon: "HD2_SEAF_Artillery",
            code: "DWWS",
            key: "mission",
        },
        {
            name: "Super Earth Flag",
            icon: "HD2_Super_Earth_Flag",
            code: "SWSW",
            key: "mission",
        },
        {
            name: "A/ARC-3 Tesla Tower",
            icon: "Teslaicon",
            code: "SWDWAD",
            key: "defensive",
        },
        {
            name: "A/M-12 Mortar Sentry",
            icon: "Mortarsentryicon",
            code: "SWDDS",
            key: "defensive",
        },
        {
            name: "A/M-23 EMS Mortar Sentry",
            icon: "EMSmortaricon",
            code: "SWDSD",
            key: "defensive",
        },
        {
            name: "A/MG-43 Machine Gun Sentry",
            icon: "MGsentryicon",
            code: "SWDDW",
            key: "defensive",
        },
        {
            name: "A/G-16 Gatling Sentry",
            icon: "Gatlingsentryicon",
            code: "SWDA",
            key: "defensive",
        },
        {
            name: "MD-6 Anti-Personnel Minefield",
            icon: "Minefieldicon",
            code: "SAWD",
            key: "defensive",
        },
        {
            name: "MD-I4 Incendiary Mines",
            icon: "Fireminefieldicon",
            code: "SAAS",
            key: "defensive",
        },
        {
            name: "FX-12 Shield Generator Relay",
            icon: "Shieldrelayicon",
            code: "SSADAD",
            key: "defensive",
        },
        {
            name: "E/MG-101 HMG Emplacement",
            icon: "HMGTurreticon",
            code: "SWADDA",
            key: "defensive",
        },
        {
            name: "A/AC-8 Autocannon Sentry",
            icon: "Autocannoasentryicon",
            code: "SWDWAW",
            key: "defensive",
        },
        {
            name: "A/MLS-4X Rocket Sentry",
            icon: "Missilesentryicon",
            code: "SWDA",
            key: "defensive",
        },
        {
            name: "AX/LAS-5 \"Guard Dog\" Rover",
            icon: "AX-LAS-5icon",
            code: "SWAWDD",
            key: "backpacks",
        },
        {
            name: "AX/AR-23 \"Guard Dog\"",
            icon: "AX-AR-23icon",
            code: "SWAWDS",
            key: "backpacks",
        },
        {
            name: "LIFT-850 Jump Pack",
            icon: "LIFT-850icon",
            code: "SWWSW",
            key: "backpacks",
        },
        {
            name: "B-1 Supply Pack",
            icon: "B-1icon",
            code: "SASWWS",
            key: "backpacks",
        },
        {
            name: "SH-32 Shield Generator Pack",
            icon: "SH-32icon",
            code: "SWADAD",
            key: "backpacks",
        },
        {
            name: "SH-20 Ballistic Shield Backpack",
            icon: "SH-20icon",
            code: "SASSWA",
            key: "backpacks",
        },
        {
            name: "AC-8 Autocannon",
            icon: "AC-8icon",
            code: "SASWWD",
            key: "weapons",
        },
        {
            name: "EAT-17 Expendable Anti-tank",
            icon: "EAT-17icon",
            code: "SSAWD",
            key: "weapons",
        },
        {
            name: "FLAM-40 Flamethrower",
            icon: "FLAM-40icon",
            code: "SAWSW",
            key: "weapons",
        },
        {
            name: "LAS-98 Laser Cannon",
            icon: "LAS-98icon",
            code: "SASWA",
            key: "weapons",
        },
        {
            name: "M-105 Stalwart",
            icon: "M-105icon",
            code: "SASWWA",
            key: "weapons",
        },
        {
            name: "MG-43 Machine Gun",
            icon: "MG-43icon",
            code: "SASWD",
            key: "weapons",
        },
        {
            name: "ARC-3 Arc Thrower",
            icon: "ARC-3icon",
            code: "SDSWAA",
            key: "weapons",
        },
        {
            name: "GL-21 Grenade Launcher",
            icon: "GL-21icon",
            code: "SAWAS",
            key: "weapons",
        },
        {
            name: "APW-1 Anti-Materiel Rifle",
            icon: "APW-1icon",
            code: "SADWS",
            key: "weapons",
        },
        {
            name: "RS-422 Railgun",
            icon: "RS-422icon",
            code: "SDSWAD",
            key: "weapons",
        },
        {
            name: "GR-8 Recoilless Rifle",
            icon: "GR-8icon",
            code: "SADDA",
            key: "weapons",
        },
        {
            name: "FAF-14 SPEAR Launcher",
            icon: "FAF-14icon",
            code: "SSWSS",
            key: "weapons",
        },
        {
            name: "LAS-99 Quasar Cannon",
            icon: "LAS99Icon",
            code: "SSWAD",
            key: "weapons",
        },
        {
            name: "MG-206 Heavy Machine Gun",
            icon: "MG206Icon",
            code: "SAWSS",
            key: "weapons",
        },
        {
            name: "Orbital Precision Strike",
            icon: "OrbitalPrecisionicon",
            code: "DDW",
            key: "orbital",
        },
        {
            name: "Orbital Airbust Strike",
            icon: "OrbitalAirbursticon",
            code: "DDD",
            key: "orbital",
        },
        {
            name: "Orbital 120MM HE Barrage",
            icon: "Orbital120icon",
            code: "DDSADS",
            key: "orbital",
        },
        {
            name: "Orbital 380MM HE Barrage",
            icon: "Orbital380icon",
            code: "DSWWASS",
            key: "orbital",
        },
        {
            name: "Orbital Walking Barrage",
            icon: "OrbitalWalkingicon",
            code: "DSDSDS",
            key: "orbital",
        },
        {
            name: "Orbital Laser",
            icon: "OrbitalLasericon",
            code: "DSWDS",
            key: "orbital",
        },
        {
            name: "Orbital Railcannon Strike",
            icon: "OrbitalRailcannonicon",
            code: "DWSSD",
            key: "orbital",
        },
        {
            name: "Orbital Gatling Barrage",
            icon: "OrbitalGatlingicon",
            code: "DSAWW",
            key: "orbital",
        },
        {
            name: "Orbital Gas Strike",
            icon: "OrbitalGasicon",
            code: "DDSD",
            key: "orbital",
        },
        {
            name: "Orbital EMS Strike",
            icon: "OrbitalEMSicon",
            code: "DDAS",
            key: "orbital",
        },
        {
            name: "Orbital Smoke Strike",
            icon: "OrbitalSmokeicon",
            code: "DDSW",
            key: "orbital",
        },
        {
            name: "Eagle Strafing Run",
            icon: "EagleStrafingicon",
            code: "WDD",
            key: "eagle",
        },
        {
            name: "Eagle Airstrike",
            icon: "EagleAirstrikeicon",
            code: "WDSD",
            key: "eagle",
        },
        {
            name: "Eagle Cluster Bomb",
            icon: "EagleClusterbombicon",
            code: "WDSSD",
            key: "eagle",
        },
        {
            name: "Eagle Napalm Strike",
            icon: "EagleNapalmicon",
            code: "WDSW",
            key: "eagle",
        },
        {
            name: "Eagle Smoke Strike",
            icon: "EagleSmokeicon",
            code: "WDWS",
            key: "eagle",
        },
        {
            name: "Eagle 110MM Rocket Pods",
            icon: "EagleRocketpodicon",
            code: "WDWA",
            key: "eagle",
        },
        {
            name: "Eagle 500kg Bomb",
            icon: "Eagle500icon",
            code: "WDSSS",
            key: "eagle",
        },
        {
            name: "EXO-45 Patriot Exosuit",
            icon: "EXO45icon",
            code: "ASDWASS",
            key: "vehicles",
        },
    ]
};